"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const mago_js_1 = require("./mago.js");
const tanque_js_1 = require("./tanque.js");
const luchador_js_1 = require("./luchador.js");
let Brand = new mago_js_1.Mago(980, "Brand", 10, 100);
console.log(Brand);
let Leona = new tanque_js_1.Tanque(980, "Leona", 10, 100);
console.log(Leona);
let Garen = new luchador_js_1.Luchador(980, "Garen", 10, 100);
console.log(Garen);
Garen.atacar();
